site_name: inband


theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
  features:
#   - navigation.instant
  - navigation.tabs
  - navigation.sections

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
# - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences


nav:
  - home: 'index.md' 
  - about: 'about.md'
  - crypto:
    - x509: 'crypto/x509.md' 
# - service provider:
  - vpn: 
    - ipsec:
      - site-to-site:
        - pre-shared-keys:
          - cisco: 'vpn/ipsec/site-to-site/pre-shared-keys/cisco.md' 
#    - openvpn:
#    - l2tp:
#    - mpls:
#  - voip: 

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
# type: date (default)
      timezone: Australia/Melbourne
      locale: en
      fallback_to_build_date: false
      exclude:
        - index.md
        - about.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inband
      name: inband (github)


